### ISSUE TITLE
Add content in the readme to let users know about editing and publishing blogs

### ISSUE THREAD

**Issue by hi-Kartik2004** [hi-Kartik2004/CraftFolio#8]
Add content in the readme to let users know about editing and publishing blogs

**Comment by hi-Kartik2004** [comment]
@mythili953 can you take over this?

**Comment by mythili953** [comment]
> @mythili953 can you take over this?

Sure

**Comment by hi-Kartik2004** [comment]
Next time you raise a Pull request addressing a issue make sure you mention which issue it closes in the title and the description of the pull request, like `closes #id_of_the_issue`

I shall mark this issue closed as its already fixed in #10
